### ISSUE TITLE
Skips AuthorizingProcessor?

### ISSUE THREAD

**Issue by nozpheratu** [venuu/jsonapi-authorization#100]
I noticed that for only my `UserResource`, the `JSONAPI::Authorization::AuthorizingProcessor` processor seemed to be getting skipped, and thus, not of the authorization callbacks trigger.

I'm working off of v1.0.0.beta1.

At this point, I'm not certain how to further diagnose this issue. 

My User resource doesn't have any fancy namespacing or anything, and is in-line with all my other resources where the AuthoirizingProcessor gets picked up.

**Comment by nozpheratu** [comment]
Disregard this, apparently it was my customer `UserProcessor` that was preventing the `AuthorizingProcessor` from getting picked up.

**Comment by valscion** [comment]
Yeah, that can indeed be tricky. Would you like to add this troubleshooting tip to the readme in "Troubleshooting" section? https://github.com/venuu/jsonapi-authorization#troubleshooting
