### ISSUE TITLE
Support Pundit v2 (and keep Pundit v1 support)

### ISSUE THREAD

**Issue by valscion** [venuu/jsonapi-authorization#103]
Hi there, community!

We would like `jsonapi-authorization` to support Pundit v2 while maintaining support for v1.

This likely means some infrastructure work to test this gem with both versions.

We should use only those Pundit features that are available in both v1 and v2 for now.

**This issue is a contribution opportunity for anyone!** Please comment below if you'd like to try to tackle this.

**Comment by jpalumickas** [comment]
Opened PR https://github.com/venuu/jsonapi-authorization/pull/104 for this.

**Comment by valscion** [comment]
Released support for Pundit v2 via #104 to new beta `v1.0.0.beta2` — thanks @jpalumickas!
