### ISSUE TITLE
Strict authorize when getting related resources

### ISSUE THREAD

**Issue by minhyeok4dev** [venuu/jsonapi-authorization#126]
Is there any way to deny a request in ordinary #index but allow in related #index? (ex. `/posts`  will be denied, `/users/1/posts` will be allowed with scope)

**Comment by valscion** [comment]
Create a new authorizer class that inherits from `DefaultPunditAuthorizer` and overwrite this method:

https://github.com/venuu/jsonapi-authorization/blob/197ee078e170744fb749b67144b873d38bcf4795/lib/jsonapi/authorization/default_pundit_authorizer.rb#L72-L83
