### ISSUE TITLE
record is received as a model class instead of an instance in the policy

### ISSUE THREAD

**Issue by foxhard** [venuu/jsonapi-authorization#136]
Hi,

I'm stuck with a thing related to received data from a POST request in a Policy.
I'm using `jsonapi-authorization (3.0.2)`

I hope you can help me. Thanks in advance :pray:

**Problem description**
After perform the API request,  the `record` parameter in `CarPolicy` constructor will be received as a class of `Car` model instead of an instance of the same class so I can't access to the values sent from the API request like `brand` ("Audi") and `model` ("A4 Sedan") by using `record.brand` or `record.model`

**Resource**
```ruby
class CarResource < BaseResource
  attributes :brand, :model
  
  def create?
    true
  end
end
```

**Policy**
```ruby
class CarPolicy     
  def initialize(user, record)
    puts record.inspect #output: Car(id: integer, brand: string, model: string, created_at: datetime, updated_at: datetime)
  end
end
```

**API Request**
`POST /api/cars`
```json
{
  "data": {
    "type": "cars",
     "attributes": {
         "brand": "Audi",
         "model": "A4 Sedan"
      }
  }
}

```

**Comment by valscion** [comment]
Yes this is as specified, please read the documentation.

**Comment by valscion** [comment]
Oh true, the docs I linked above might seemingly not talk about your case. But using the class in `create?` is expected. You can search existing closed or open issues for more information and link them here for future wonderers :)

**Comment by foxhard** [comment]
For those who also might be encountering a problem like this,  I found the solution in this [issue](https://github.com/venuu/jsonapi-authorization/issues/86)
