### ISSUE TITLE
Per resource authorizers

### ISSUE THREAD

**Issue by RSSchermer** [venuu/jsonapi-authorization#14]
First of all: love this gem, thanks a lot!

I'm running into a bit of an issue with [this bit of code in the DefaultPunditAuthorizer](https://github.com/venuu/jsonapi-authorization/blob/c2e392ac6f9d14da7857ac1ecafb6146f665c9a3/lib/jsonapi/authorization/default_pundit_authorizer.rb#L113-L115). It seems like excellent default behavior, but does not seem compatible with my use case:

Models: `User`, `Project`, `Invitation`.
Relationships:
`User` one-to-many `Invitation`
`Project` one-to-many `Invitation`

As a project admin wants to create a user to the project by creating a new Invitation. However, the project admin cannot `update?` that user. Therefore a `Pundit::NotAuthorizedError` is raised.

One solution that springs to mind is to define a custom authorizer for `Invitation`. Looking at [this snippet](https://github.com/venuu/jsonapi-authorization/blob/c2e392ac6f9d14da7857ac1ecafb6146f665c9a3/lib/jsonapi/authorization/authorizing_operations_processor.rb#L186-L188), it seems that currently this is not possible and only one global authorizer can be specified? Perhaps it would be possible to allow specifying per resource authorizers, maybe something along these lines:

```ruby
class InvitationResource < JSONAPI::Resource
  include JSONAPI::Authorization::PunditScopedResource

  authorizer InvitationAuthorizer

  has_one :user
  has_one :project

  ...
end
```

I would then define an `InvitationAuthorizer` that extends the `DefaultPunditAuthorizer` and overrides `create_resource`. Perhaps this could also be a first step towards decoupling from Pundit (e.g. one could just define a set of custom authorizers, rather than a set of policies), which might be nice.

If this seems like a decent idea and we can agree on what the interface should look like, I'd be happy to look into making a PR that implements this.

**Comment by valscion** [comment]
Hi! Awesome to see interest in this project. We have a busy day today so we might not be able to respond as swiftly as usual. We'll discuss this with @lime and get back to you soon :)

**Comment by lime** [comment]
Hi @RSSchermer, thanks for the suggestion and sorry for the delay.

This is an interesting, and challenging, question. If we take a look at the current components and their roles, it goes something like this:

1. OperationsProcessor: the part that ties into jsonapi-resources, sometimes digging deep into private API to get the details we need. Does the dirty work.
2. Authorizer: a more customization-friendly layer between the resource operations and your authorization logic, usually provided by...
3. Policies: in the default case, Pundit policies tied to the standard Rails actions.

Now, I guess the question is: at which layer should we inspect the type of resource we have, and pass it on to a model-specific handler? Currently it happens in the Authorizer, so you have only one Authorizer but multiple policies. I'm reluctant to duplicate that same responsibility by having multiple Authorizers.

The Authorizer also maps JSONAPI operations to Rails/Pundit default actions. The number of actions is pretty small, and thus you find yourself in a situation where the mapping is too limited.

An option we initially considered when writing this gem was to create an Authorizer which calls much more specific actions on the policies, e.g. `create_relationship?`. That would come pretty close to what you are suggesting, and make it easier to define more granular permissions on the policy level.

One reason we didn't, was to avoid adding too much complexity for new users trying out jsonapi-authorization.

Another reason is that, to answer the question of `create_relationship?`, you usually need both the source record and the related record. Passing multiple records to a policy is [explicitly discouraged](https://github.com/elabs/pundit#additional-context) by Pundit, so we'd have to create our own wrapper or other convention there. Or create some custom non-Pundit type of policies.

With that being said, I would _love_ for us to create a more sophisticated Authorizer, and include it in the project as a suggested option to use when you reach the limits of DefaultPunditAuthorizer. That would give us all a simple default setup, with a common convention for more advanced, granular control.

Sorry for the wall of text. I'm dumping quite a lot of thoughts here, but I want to stress that nothing is set in stone. This is just the reasoning behind our decisions until now. I would love to hear your thoughts.

**Comment by RSSchermer** [comment]
Hi @lime, thanks for the reply!

I've thought about more specific actions/methods on policies as well. Here are my thoughts thus far:

Perhaps rather than specifying a single `create_relationship?` method that needs to receive a related record, a policy could specify separate methods for each relationship following a standard naming scheme, for example `link_<relationship_name>?` (or `update_<relationship_name>?` or perhaps there's a better word altogether). In my example above the  `UserPolicy` could define a method named `link_invitations?`. The `DefaultPunditAuthorizer#create_resource` method could then look for the relationship specific method and fall back to `update?` if no such method is defined. That might look something like this:

```ruby
def create_resource(source_class, related_records)
  ::Pundit.authorize(user, source_class, 'create?')

  related_records.each do |record|
    policy = policy!(user, record)
    relationship_name = ... # Not sure how you would resolve this
    link_query =  "link_#{relationship_name}"
    query = policy.respond_to?(link_query) ? link_query : :update?

    unless policy.public_send(query)
      raise ::Pundit.NotAuthorizedError, query: query, record: record, policy: policy
    end
  end
end
```

However, a problem with this approach is that I currently wouldn't know how you'd resolve the relationship name. If we can figure that out though, then perhaps the upside of this approach is that you could probably address a great number of use-cases without having to pass multiple records to a policy. You could perhaps also do a similar thing for read access to relationships (e.g. `show_<relationship_name>?` falling back to `show?`).

I think finer grained policy control would indeed be very nice and could probably address my current use-case. However, it seems that although we might be able to achieve finer grained control at the policy level there may still be limitations, whereas perhaps at the authorizer level more complete control can be achieved. More control at the policy level and more control at the authorizer level might be separate issues?

Anyway, just my two cents. I'm sure that if we braindump enough, eventually we'll be able to distill some sensible ideas out of the puddle.

**Comment by aaronbhansen** [comment]
I don't know if this would help, but I stubbed out an idea on pundit issues since we also needed multiple authorizers based on the current user context. https://github.com/elabs/pundit/issues/379#issuecomment-207020283

**Comment by valscion** [comment]
> However, a problem with this approach is that I currently wouldn't know how you'd resolve the relationship name.

We've thought of this as well. We'd like to keep the Authorizer away from JSONAPI Resources specific stuff and only handle records as it would make the implementation only concerned of the actual records underneath. I'm afraid if we'd try to extract more information from resource models/classes/relationships, the code would get a lot more complex and updating to a new version of JR could get more cumbersome.

> I think finer grained policy control would indeed be very nice and could probably address my current use-case.

I agree, and it's most likely that finer grained policy controls would work for you.

> However, it seems that although we might be able to achieve finer grained control at the policy level there may still be limitations, whereas perhaps at the authorizer level more complete control can be achieved.

This could be, but I'd like us to first try out the finer grained policy control route and then see if it still isn't enough.

> More control at the policy level and more control at the authorizer level might be separate issues?

Yeah, quite possibly. I'd suggest we keep on discussing the "more control at policy level" in #15 and close this issue to keep the discussion in one place. What do you think?

**Comment by RSSchermer** [comment]
@valscion Yes, closing and moving the discussion to #15 for now is fine by me!

**Comment by valscion** [comment]
Please see #30 for a possible solution to this problem. Any input in there is greatly appreciated!
