### ISSUE TITLE
pundit_user can not be modified

### ISSUE THREAD

**Issue by Babar-Livestorm** [venuu/jsonapi-authorization#142]
Hi I am using version 3.0.2 of the gem, and I am trying to change the pundit_user, but no success, I followed the documentation provided. But the code breaks on line 317 of pundit.rb
NameError:
        undefined local variable or method `current_user'.
I tried overriding the pundit_user in the controller as well. but it doesn't make a difference.
Any help would be appreciated.

**Comment by valscion** [comment]
Can you make a small, minimal reproduction repository showcasing the issue?
