### ISSUE TITLE
Is it possible to use `verify_authorized` with this gem?

### ISSUE THREAD

**Issue by barendt** [venuu/jsonapi-authorization#16]
Please forgive me if I'm doing something wrong, missing the point, or just flat-out not making sense here. I'm new to this gem, new to the JSON API Resources gem, and new to Pundit so I may be totally wrong here.

I've got a Rails 5 app (using beta 3) that is using jsonapi-authorization and jsonapi-resources with the `DefaultPunditAuthorizer`. I've configured this gem as instructed in the README. What I'm seeing is that Pundit authorization and scoping are being performed, but that the `verify_authorized` and `verify_policy_scoped` actions are still raising `Pundit::AuthorizationNotPerformedError`.

I believe this is because `DefaultPunditAuthorizer` is using `Pundit.authorize` (the class method) instead of `Pundit#authorize` (the instance method). The two are similar, but one of the differences appears to be that `Pundit.authorize` doesn't set the `@_pundit_policy_authorized` flag so, when the `verify_authorized` action runs, Pundit thinks the request was never authorized.

Does that make sense or have I screwed something up in my project?

If I'm not doing something wrong and this sounds like a feature you'd be willing to merge, I'd be happy to come up with a way to implement and then prepare a PR. Thanks!

**Comment by aaronbhansen** [comment]
I ran into this too. see if this fixes it on your application policy.

```
def scope
    if record.class == Class
      Pundit.policy_scope!(user, record)
    else
      Pundit.policy_scope!(user, record.class)
    end
  end
```

**Comment by barendt** [comment]
Thanks for the suggestion, but I don't think that does it. In both cases that's still just calling the class method (https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L90) which doesn't set the instance variable that `verify_policy_scoped` is checking to see if the request has had scoping performed.

I think the trick here is both `verify_policy_scoped` and `verify_authorized` are expecting the instance variables to be set in the controller so there's not really anything the individual policies can do to affect that. As far as I can tell, this is the connection between JR and jsonapi-authorization (https://github.com/cerebris/jsonapi-resources/blob/master/lib/jsonapi/acts_as_resource_controller.rb#L56). That doesn't really leave much room for us to access those instance variables in the controller.

For now, I've added two methods to my `ApplicationController`:

```ruby
def mark_action_as_authorized
  @_pundit_policy_authorized = true
end

def mark_action_as_scoped
  @_pundit_policy_scoped = true
end
```
and then used those in individual controllers:
```ruby
class ClientsController < ApplicationController
  before_action :mark_action_as_authorized, only: [:create, :destroy, :show, :update]
  before_action :mark_action_as_scoped, only: :index
```
it's not as pretty as I'd like, but it will get the job done and make sure we don't ever accidentally add a new action to a controller without remembering to use Pundit for authorization and scoping.

**Comment by valscion** [comment]
Hi, and thanks for trying this gem out!

I think that the `verify_authorized` and `verify_policy_scoped` don't make much sense together with this gem. Those verifications only provide very rudimentary protection — mainly, that any sort of authorization calls have happened.

As those [checks are opt-in](https://github.com/elabs/pundit#ensuring-policies-and-scopes-are-used), I suggest you don't apply them in your JSON API controllers which also use this gem. If you're inheriting from a controller which has the `after_action` filter defined, just skip it in your JSON API controllers where you're using this gem

**Comment by barendt** [comment]
Thanks, @valscion, for making the gem!

I see where you're coming from. In my case I'd prefer to have these checks, rudimentary as they are, in place just for an extra bit of comfort so no future developer on this project adds a new action to any controller (including JSON API controllers) without giving authorization some thought. Your point totally makes sense, though, so I'll just keep going with the `before_action` approach as that's working just fine. Thanks again!

**Comment by jaydorsey** [comment]
I just ran into this issue as well, after integrating this gem around a pundit config someone else setup. Would be nice to see even a warning (console is fine), or an update to the README if adding this integration to the road map isn't planned. 

While the check it performs is pretty rudimentary, it's a documented pundit feature. Since this gem is supposed to marry jsonapi-resources & pundit it would be better behavior to support it. I need to do a little more digging but I'll think about opening a PR for this once I'm done with my integration.
