### ISSUE TITLE
Relax jsonapi-resources version constraint?

### ISSUE THREAD

**Issue by arcreative** [venuu/jsonapi-authorization#17]
Can you drop the `.0` off of jsonapi-resources `0.7.0` please?  Trying to get this working with the new beta, but bundler is yelling about it!

**Comment by valscion** [comment]
We intentionally wanted to constrain this gem to a single version as we're reaching to quite a lot of JR internals. That being said, I don't think the beta has changed the internals much..? @arcreative can you create a PR which would run the tests against the beta version of JR, and relax the gemspec constraints? If all the tests pass, I suppose we'd be confident enough to allow running beta, too.

**Comment by arcreative** [comment]
I think that's reasonable--I don't really think the beta is going to fix my current problems, unfortunately...

**Comment by lime** [comment]
FYI @arcreative, we've now released version 0.6.1 of the gem with a more permissive version constraint, you might want to take it for a spin. :)

**Comment by arcreative** [comment]
@lime Awesome, thanks!  Probably come in handy with an impending Rails 5 upgrade as well :-)
