### ISSUE TITLE
Having issues with create/update

### ISSUE THREAD

**Issue by GRardB** [venuu/jsonapi-authorization#21]
Finally got around to checking this gem as per @valscion's suggestion!

I'm using Ember.js, and I'm having some issues with my create/update calls. An example of a model relationship I have is:

`Expense belongs to a User`
`Expense belongs to a Category`

When I try to create or update an `Expense`, I get a an error saying that I don't have permission to update a `Category` (which I shouldn't). If I make the `Category` update-able by every user, I then get an error saying that I'm unable to update the user (I should, but technically I haven't implemented that part yet).

I'm confused as to why I'd need to set up permissions for these models since I'm not updating them in any way. I'm especially concerned with `Category`'s permissions, given that I definitely don't want every user to be able to update that model. Any ideas?

Thanks!

**Comment by GRardB** [comment]
Another similar issue I'm running into:

`Group belongs to User (owner)`
`Group belongs to User (member)`
`Group has many Invitations`

`Invitation belongs to User (member)`
`Invitation belongs to Group`

When I try to *accept* an invitation as a `member`, I get an error saying this `User` doesn't have permissions to update the `Group` (because the `member` is not the `owner`). However, I don't see why the member would need permissions to update the `Group` in order to update an `Invitation`.

**Comment by GRardB** [comment]
Just realized this is a duplicate. Sorry!

**Comment by valscion** [comment]
Please see #30 for a possible solution to this problem. Any input in there is greatly appreciated!
