### ISSUE TITLE
Not compatible with upcoming operation processing

### ISSUE THREAD

**Issue by valscion** [venuu/jsonapi-authorization#22]
Changes done in https://github.com/cerebris/jsonapi-resources/pull/694 will affect this gem and we'll need to update the gem to be compatible with upcoming JR versions due to this change.

**Comment by acid** [comment]
Hmm, as far as I can see it should be enough to inherit the custom processor from `JSONAPI::Processor` as this one now provides the callbacks we're hooking in.

**Comment by valscion** [comment]
Oh nice, that would be amazing if that were true :) There might be some surprises on the way, though, as we're relying on lots of internal-ish stuff of JR.

Do you wanna give it a shot? :smile: I can help you get started if you're having problems

**Comment by acid** [comment]
I will give it a shot in the afternoon and provide you with either a pull request or some feedback :)

**Comment by valscion** [comment]
Super, cheers! 💞

**Comment by acid** [comment]
Ok, I gave it a quick shot. Got our specs running by renaming all the callbacks and changing the default processor option in the initializer. After that I changed `@operation.resource_klass` to `@resource_klass` and then I ran into the switch cases against @operation.

I think it's doable and not that much work but I have other things to do today. Hopefully I can find some time for that next week but no guarantees!

**Comment by valscion** [comment]
Great! I'll ask again after next week if you've been too busy to do anything ☺️ . Thanks for the initial work :+1:

**Comment by lynndylanhurley** [comment]
I'm stuck on this - @acid is there a quick fix?

**Comment by acid** [comment]
Well, the fix wasn't quick but definitely worth it. I did a pull request, but it's unfinished as model_includes aren't validated right now. https://github.com/venuu/jsonapi-authorization/pull/24

If somebody has an idea what's causing the bug on the model includes I would be glad. Otherwise I will investigate this soon, shouldn't be that hard.

**Comment by valscion** [comment]
I just released [v0.8.0](https://github.com/venuu/jsonapi-authorization/releases/tag/v0.8.0) that is compatible with upcoming JR v0.8.0 version. Thanks to @acid! :tada:
