### ISSUE TITLE
PunditScopedResource cannot find relationship by assocation_name

### ISSUE THREAD

**Issue by mytram** [venuu/jsonapi-authorization#35]
Hi, 

I just would like to report this issue. 

In PunditScoopeResource's #records_for, it uses the association_name, which is  relation_name: when defining relationships. relation_name: can differ from the relationship name. 

The relationship hash (self.class._relationships) is indexed by relationship names. So if these two names differ, it will fail to find the relationship. 

Many thanks,

**Comment by valscion** [comment]
Oh yeah, that might be true. I guess we do handle these sorts of situations in [the processor side](https://github.com/venuu/jsonapi-authorization/blob/v0.8.1/lib/jsonapi/authorization/authorizing_processor.rb#L233-L235), but not on the `PunditScopedResource` side. 

It would help a lot if you, or someone else, would be able to provide at least a failing test case for this issue. Here's some tips how setting the test up could look like:

* Add a relationship that uses `relation_name` to e.g. [`ArticleResource` in the dummy test app](https://github.com/venuu/jsonapi-authorization/blob/v0.8.1/spec/dummy/app/resources/article_resource.rb).
* Add a new test case to [relationship operations spec file](https://github.com/venuu/jsonapi-authorization/blob/v0.8.1/spec/requests/relationship_operations_spec.rb) that tries to use the new relationship that uses `relation_name`

It can be quite handy to put `binding.pry` inside the [`PunditScopedResource#records_for` method](https://github.com/venuu/jsonapi-authorization/blob/v0.8.1/lib/jsonapi/authorization/pundit_scoped_resource.rb#L16) to check out what you can ask from the resource class as well as the relationship that you can get from the resource class.

If you've never used [`pry`](https://github.com/pry/pry) debugger before, once you hit the `binding.pry` line you'll get a debug view inside your shell/terminal. `help` command shows the commands you can run inside pry. I'd suggest trying out `ls` command to see what is available to you at the debug point to get started, and then check further by using `ls` on some variable or method (e.g. `ls self.class` would show you what is available on the resource class).

Let me know if I can help you in debugging this further! We'll really appreciate a PR to fix this, or to come up with a test case, if someone wants to give it a try :+1:

**Comment by bsofiato** [comment]
Guys. I've issue a PR #42 which should resolve this particular issue.

**Comment by valscion** [comment]
Closed by #42
