### ISSUE TITLE
Not compatible with v0.9.0 of jsonapi-resources

### ISSUE THREAD

**Issue by valscion** [venuu/jsonapi-authorization#36]
I believe that changes done in https://github.com/cerebris/jsonapi-resources/pull/845 will be incompatible with what we're running with in here.

Adding an issue so it won't come as a surprise to us.

**Comment by valscion** [comment]
> Any plan to support the new version of jsonapi-resources, are there some issues preventing this gem to be compatible yet?

Changes in https://github.com/cerebris/jsonapi-resources/pull/845 changed the relationship operation names, and thus breaks our callbacks, too.

> We would like to enable the new caching feature of 0.9 but we cannot upgrade because of the dependency lock on 0.8.
> 
> How could we help? Thanks!

If you could look into what kind of a version check we'd need to implement to support 0.8 and 0.9 versions of JR and submit a PR, that would be great ☺️. We'd need to make sure that Travis runs successfully on both 0.8 version and v0.9.0.beta3 version of `jsonapi-resources` for the PR to be acceptable.

We're not yet testing out 0.9 version of JR as it's beta, but a PR to support both 0.8 and 0.9 would be appreciated :+1:

**Comment by valscion** [comment]
We'd like to have help tackling this issue! If you want to start tackling this, please leave a comment so others won't waste effort on the same task ☺️

We'd want to get this compatibility fixed for v1.0.0 release, if at all possible.

**Comment by d4rky-pl** [comment]
If #52 was merged, does that mean this issue is already solved? :)

**Comment by valscion** [comment]
Oh yeah, good point. I thought that I had closed this issue already 😅 .
