### ISSUE TITLE
Documentation on updating processors to use `AuthorizingProcessor`?

### ISSUE THREAD

**Issue by arcreative** [venuu/jsonapi-authorization#38]
Sorry to keep coming up with these weird issues, but I just had a hell of a time debugging an issue where a custom processor was extending `JSONAPI::Processor` instead of `JSONAPI::Authorization::AuthorizingProcessor`, and refused to use the pundit policy at all.  It was just a fluke that I caught this, and I'm really wishing there were a stronger safeguard to prevent me from leaving resources completely unauthorized in the future.  Is there some sort of monkey patch for `JSONAPI::Processor` that should log/fail/notify if you're using the wrong one?  Seems like very dangerous behavior for pretty reasonable development behavior.

I had the following, as documented in `JSONAPI::Resources` docs:

```rb
module Api
  module V1
    class MyWhateverProcessor < JSONAPI::Processor
      after_find do
        # Do the stuff
      end
    end
  end
end
```
...which seems reasonable, and was very hard to track down!  Any thoughts?  Or is this just going too much out of the way?  Or maybe just mention something in the README?

**Comment by valscion** [comment]
Oh yikes! That sounds really unfortunate. I have no idea how to possibly warn about this sort of Ruby behaviour. Maybe this could be resolved on the `jsonapi-resources` level instead? Like add a new configuration option to JR that would disallow configuration set processor from being overridden 😕 

I'd be very happy to accept a PR that notes about this caveat in our repository, though. I suppose you know the best how to put this danger into words, as you've been stinged by it yourself 😅

**Comment by arcreative** [comment]
@valscion Thanks, will take a whack at the README here--I think since the readme is short and succinct, a small note about it should be good for all but the laziest of us :-)

**Comment by valscion** [comment]
Hiya @arcreative — would you still like to add that note to the README or should we close this issue?

**Comment by arcreative** [comment]
@valscion Yeah, thanks, will try to look at it next week
