### ISSUE TITLE
CI doesn't correctly run tests against master version of jsonapi-resources

### ISSUE THREAD

**Issue by valscion** [venuu/jsonapi-authorization#41]
We've got something wrong with the gem specifications and/or TravisCI setup, such that the tests against `master` version of `jsonapi-resources` aren't actually ran at all. This can be seen from e.g. this test run: https://travis-ci.org/venuu/jsonapi-authorization/jobs/186102969

If anyone wants to chime in and help with this, please do so :). This could be a good first PR to handle! If you have any questions, I'll try to answer to the best of my knowledge.

**Comment by nruth** [comment]
It looks like this has been fixed and can be closed? https://travis-ci.org/venuu/jsonapi-authorization runs through. Probably to do with moving from a beta JR version (that it couldn't find) to 0.9.

**Comment by valscion** [comment]
Ah, unfortunely no. We'll likely need something along the lines I deleted in #57 in the `.travis.yml`:

```diff
 env:
   - JSONAPI_RESOURCES_VERSION=0.9 RAILS_VERSION=4.1.0
   - JSONAPI_RESOURCES_VERSION=0.9 RAILS_VERSION=4.2.0
+  - JSONAPI_RESOURCES_VERSION=master RAILS_VERSION=4.2.0
+  - JSONAPI_RESOURCES_VERSION=master RAILS_VERSION=4.1.0
 rvm:
 - 2.1.2
 before_install: gem install bundler -v 1.11.2
+matrix:
+  allow_failures:
+    - env: JSONAPI_RESOURCES_VERSION=master RAILS_VERSION=4.2.0
+    - env: JSONAPI_RESOURCES_VERSION=master RAILS_VERSION=4.1.0 
```

So currently we're not even trying to run the specs against `master`.

**Comment by nruth** [comment]
Sorry I completely misread this issue and thought it was saying the CI didn't run against the master of this project repo (i.e. couldn't test itself).
