### ISSUE TITLE
JSONAPI::Resources 0.9 support

### ISSUE THREAD

**Issue by thibaudgg** [venuu/jsonapi-authorization#46]
Any plan to support the new version of jsonapi-resources, are there some issues preventing this gem to be compatible yet?

We would like to enable the new caching feature of 0.9 but we cannot upgrade because of the dependency lock on 0.8.

How could we help? Thanks!

**Comment by valscion** [comment]
Closing as a duplicate of #36, I'll answer there :)

**Comment by thibaudgg** [comment]
Ok, thanks @valscion.
