### ISSUE TITLE
Does this library guarantee authorization for all resources?

### ISSUE THREAD

**Issue by iamvery** [venuu/jsonapi-authorization#50]
I recently inherited a project that uses this library for authorizing jsonapi-resources. After reading your README, I get the feeling that this project ensures that all resources using your "authorizing processor" are guaranteed authorized. Said differently, your authorizing processor requires a Pundit policy exist for every resource and will be used to authorize every request.

**Is my understanding correct? Can I assume that all resources and all actions will be authorized?**

Under that assumption, did you consider using Pundit's [`verify_authorized`](https://github.com/elabs/pundit#ensuring-policies-and-scopes-are-used) method to enforce that truth?

Thanks so much for you hard work on a useful tool! ❤️

**Comment by valscion** [comment]
Hi! Yes, all resources and actions should be authorized. If that is not the case, it is a serious bug.

About `verify_authorized`, I commented on the false sense of security it provides here: https://github.com/venuu/jsonapi-authorization/issues/16#issuecomment-211803964 and why we don't think they provide additional protection.

**Comment by iamvery** [comment]
Thanks for the quick response! Knowing that I should be able to trust this library in that way will help me adjust my own testing approach and should simplify things. And also, thank you for pointing out that discussion. I'm sorry I didn't manage to find that on my own. I should have done more thorough searching.

Thank you again! Have a wonderful say 🙂

**Comment by valscion** [comment]
No problem :) do note that we haven't yet shipped version 1.0.0 with support for relationship methods, so you might have some issues with authorizing with anything else than `update?` on relationship operations.

You can chime in on #48 if you'd like to help with getting to v1.0.0 :)

**Comment by arcreative** [comment]
@iamvery One thing maybe worth mentioning is that if you're using a custom processor, it must extend the `AuthorizingProcessor` to ensure authorization.  I ran into this issue in one of my projects, but other than this, it all seems pretty safe :-)

**Comment by iamvery** [comment]
Makes sense @arcreative. Thanks for the heads up! ❤️
