### ISSUE TITLE
"Not allowed to update? this <object>" when underlying class name is different

### ISSUE THREAD

**Issue by mroach** [venuu/jsonapi-authorization#55]
I'm using jsonapi-resources v0.9 and the current bleeding edge jsonapi-authorization for 0.9. This issue is happening under RSpec.

Base model:

```
class Business
  belongs_to :category, class_name: BusinessCategory, counter_cache: true
end
```

Resource:

```
class BusinessResource < BaseResource
  relationship :category, to: :one
end
```

The issue is when I attempt to create a `Business` and set the `category` relation, I get the pundit error `not allowed to update? this <BusinessResource...` which doesn't make sense to me since the underlying model shouldn't be touched (I've tried removing `counter_cache` to be sure). The given user does indeed not have permission to modify business categories but they have permission to create businesses. All my policy tests pass to confirm this. So the issue is somewhere in the JSONAPI layer.

Here's what I'm doing to create it:

```
attrs = attributes_for(:business)
category_id = create(:business_category).id

params = {
  data: {
    type: 'businesses',
    attributes: attrs,
    relationships: {
      category: {
        data: {
          type: 'business-categories',
          id:   category_id
        }
      }
    }
  }
}

post "/api/v1/businesses", params: params, headers: headers, as: :json
```

Is this not supported, is there a bug, or am I doing something wrong?

**Comment by valscion** [comment]
Hiya! Thanks for the thorough issue :)

#51 would probably be what would allow you to get rid of the authorization of `update?` for the `BusinessCategory` model and would allow you to instead use `BusinessPolicy#add_category(new_category)?` method.

As #51 isn't yet done, we don't yet support finer grained permissions for operations using relationships on the resource level operations, I'm afraid.

You could work around this by creating the `Business` first and then sending a relationship operation afterwards:

```rb
attrs = attributes_for(:business)
category_id = create(:business_category).id

params = {
  data: {
    type: 'businesses',
    attributes: attrs
  }
}

post "/api/v1/businesses", params: params, headers: headers, as: :json

relationship_params = {
  data: {
    type: 'business-categories',
    id:   category_id
  }
}

post(
  "/api/v1/businesses/relationships/category",
  params: relationship_params,
  headers: headers,
  as: :json
)
```

**Comment by mroach** [comment]
Thanks for the response! I had taken a look at those issues but didn't think they applied. I realise I didn't explain exactly what I was getting at here. There's parent record here `BusinessCategory` that's configured by site admins. Any user can setup a `Business`. They do not have permission to modify the parent or create new parents. At the base level all that's happening is the `business_category_id` is being set on the newly created `Business` record. It's the same dynamic as a user being allowed to comment on a blog post but have no permission to create or edit posts. Are you saying that even in a case like this, `update?` is being checked for the parent record? Or is this a thing that it's considered an update to the parent if you add a child?

Unfortunately for me (and I suspect many/most others), model validations and database constraints will forbid creating child records without the parent. Non-nullable fields and all that jazz.

I'm happy to see that issue #51 is actively being worked on!

**Comment by valscion** [comment]
> Or is this a thing that it's considered an update to the parent if you add a child?

Yup, that is exactly it. We consider relationships to touch both sides of the association, no matter where the foreign key lives in, so we authorize for that case.

I agree that the situation isn't perfect yet, but we want to err on the side of being overly restrictive than accidentally let people do stuff they shouldn't be allowed to do.

**Comment by mroach** [comment]
Now that I understand your methodology this all makes sense then. So thank you for the explanation! And thanks for this gem!

**Comment by valscion** [comment]
Thank you! You aren't the first one to get confused by this. Do you think you'd be able to whip up an explanation to the README about this situation? I have a hard time putting this to words from an outside perspective, so a PR explaining our stance on authorizing relationships would be highly appreciated ☺️
