### ISSUE TITLE
Is it possible to make a filter mandatory with this library?

### ISSUE THREAD

**Issue by benarmston** [venuu/jsonapi-authorization#68]
I wish to allow clients to be able to lookup a resource with some lookup key.  Unfortunately, that lookup key is not the primary key for that resource.  This is easily done by having the client make a request such as:

```
GET https://localhost/my-resource?filter[name]=some-name
```

Now for the more tricky part.  I wish to prevent the client from obtaining a list of all the resources. By this I mean that the following, would result in a  400 Bad Request respeonse.

```
GET https://localhost/my-resource
```

I can achieve this with a `before_find` callback on the `MyResourceProcessor`. E.g.,

```ruby
class MyResourceProcessor < JSONAPI::Processor
  before_find do
    unless params[:filters][:name].present?
      raise JSONAPI::Exceptions::ParameterMissing.new('filter[name]')
    end
  end
end
```

And similar for `show_related_resources` and perhaps `show_related_resource`.

My question is, how would I integrate that rule with jsonapi-authorization?  Is there a way to add that check to `AuthorizingProcessor`? Or a way to include a similar check in the policy?

**Comment by valscion** [comment]
You might be able to get your custom resource processor logic by sub-classing [`JSONAPI::Authorization::AuthorizingProcessor`](https://github.com/venuu/jsonapi-authorization/blob/v1.0.0.alpha3/lib/jsonapi/authorization/authorizing_processor.rb) for your `MyResourceProcessor`.

Currently the policies don't get any data about the used filters nor parameters, only about what is about to be created or modified.

**Comment by benarmston** [comment]
Thanks for the quick response.  Having my processor inherit from `AuthorizingProcessor` looks like it should fix the problem for me.

You say that "*currently* the policies don't get any data...".  Am I correct in reading that to mean that you would possibly be open to changing that?

**Comment by valscion** [comment]
> Thanks for the quick response. Having my processor inherit from AuthorizingProcessor looks like it should fix the problem for me.

Hopefully it will work for you :relaxed: :+1:

> You say that "*currently* the policies don't get any data...". Am I correct in reading that to mean that you would possibly be open to changing that?

We haven't given it much thought. This comment might shed some light https://github.com/venuu/jsonapi-authorization/issues/33#issuecomment-245195421

There might be a way to support param passing in a clean way in the future. An approach for that would just have to be discussed first :relaxed:

If I was able to answer your original question, could we close this issue?

**Comment by benarmston** [comment]
Yes let's close this issue.  Thanks again for your help.

**Comment by valscion** [comment]
Glad to be of help 💞. Let us know if you hit any roadblocks with the subclassing approach. We haven't had to do that ourselves so we don't have any experience in how the result looks like. If you've got better ideas in how to enable this kind of customization, we're happy to discuss it more ☺️
