### ISSUE TITLE
Using custom processor skips authorization

### ISSUE THREAD

**Issue by RitterNorbert** [venuu/jsonapi-authorization#84]
Hi

The authorization is not working if I have a processor callback.
I have a `RegistrationsController` and a `RegistrationProcessor` with an `after_replace_fields` callback and the `update?` policy is skipped. If I delete the callback the authorization is working
Any idea how to solve this?

**Comment by valscion** [comment]
Hi! Thanks for opening an issue :)

Could you care to elaborate a bit on how your code looks like? Maybe even show me the relevant pieces of code? I don't really understand right now what you are saying.

Thanks!

**Comment by RitterNorbert** [comment]
solved :)
class V1::RegistrationProcessor < JSONAPI::Processor
had to be changed to 
class V1::RegistrationProcessor < JSONAPI::Authorization::AuthorizingProcessor

**Comment by valscion** [comment]
Oh yes, that is true. You'll need to manually merge our authorizing processor functionality in if you use your own processors.

Would you be open to add this caveat to the "Troubleshooting" section in the README?

**Comment by valscion** [comment]
I think this has actually been documented already.
