### ISSUE TITLE
How to check whether a specific record can be created

### ISSUE THREAD

**Issue by adambedford** [venuu/jsonapi-authorization#86]
The `create` policy action receives the model class, rather than the built instance, so I'm wondering what the guidance is on authorizing creation of specific records/attributes.

The use case is to ensure admins can only create records for users on their account. The policy scope handles this for read operations, and the `update` action can handle updates, but is there a good way to do it for creates?

**Comment by valscion** [comment]
Hi,

sorry, for cases where you need to check incoming `params`, this library does not yet support that use case.

See #33 for a similar issue.

Unfortunately, you will have to rely on methods/hooks provided by `jsonapi-resources` to achieve that.
