### ISSUE TITLE
Did not work with JR 0.9.0

### ISSUE THREAD

**Issue by jonasmedeiros** [venuu/jsonapi-authorization#91]
Hey tried to use the gem could not

**Comment by valscion** [comment]
Hi! We are using this gem with JR 0.9.0 so I can't help you unless you provide me with more information.

**Comment by Pungsnigel** [comment]
Isn't latest version depending on jsonapi-resources 0.8.x?

**Comment by valscion** [comment]
Oh yeah, sorry. The latest released 0.x version is — you might have luck testing out the alpha releases of v1.0.0 :) https://github.com/venuu/jsonapi-authorization/blob/v1.0.0.alpha6/jsonapi-authorization.gemspec#L20

**Comment by ch-tactica** [comment]
@valscion What needs to happen to get this out of alpha and released to Rubygems?

**Comment by valscion** [comment]
See https://github.com/venuu/jsonapi-authorization/issues/48 for the things that need to be done / could need help from outside :)

**Comment by valscion** [comment]
I'll close this as alpha releases do indeed work with JR 0.9.0
